import { exec as execSync } from 'child_process'
import { mkdir, readFile, writeFile } from 'fs/promises'
import path from 'path'
import { promisify } from 'util'
import { pathExists } from 'fs-extra'

import GitAutocommit from './GitAutocommit.js'

export default class NpmAutopackage implements Autopackage {
    public static Class?: AutopackageConstructor
    public static exec = promisify(execSync)
    public static fetch = fetch
    public static mkdir = mkdir
    public static pathExists = pathExists
    public static readFile = readFile
    public static writeFile = writeFile

    private description: string
    private gitNamespace: string
    private npmNamespace?: string
    private keywords?: string[]
    private license?: string
    private author?: string

    private originalPackageJson?: Record<string, unknown>
    private originalGitignore?: string

    private originalTsconfig?: TsConfig
    private metaNodeVersion?: string

    private originalEslintConfig?: string
    private originalPrettierConfig?: string
    private originalSettingsJson?: string

    private originalTasksJson?: {
        tasks: unknown[]
        inputs: unknown[]
        [key: string]: unknown
    }

    private shouldOpenVscode = false

    private readonly installDir: string
    private readonly packageName: string
    private readonly packageDir: string
    private readonly packageJsonPath: string
    private readonly gitignorePath: string
    private readonly tsconfigPath: string
    private readonly tasksJsonPath: string
    private readonly testsDir: string
    private readonly abstractTestPath: string
    private readonly eslintConfigPath: string
    private readonly prettierConfigPath: string
    private readonly settingsJsonPath: string

    private readonly abstractPackageTestFile = `import AbstractModuleTest from '@neurodevs/node-tdd'

export default abstract class AbstractPackageTest extends AbstractModuleTest {
    protected static async beforeEach() {
        await super.beforeEach()
    }
}
`

    private readonly eslintConfigFile = `import eslintConfigNdx from '@neurodevs/eslint-config-ndx'

export default eslintConfigNdx
`

    private readonly prettierConfigFile = `import prettierConfigNdx from '@neurodevs/prettier-config-ndx'

export default prettierConfigNdx
`

    private readonly settingsJsonFile = `{
  "debug.node.autoAttach": "on",
  "git.ignoreLimitWarning": true,
  "javascript.validate.enable": false,
  "files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/.git/subtree-cache/**": true,
    "**/build/**": true,
    "**/node_modules/**": true
  },
  "search.exclude": {
    "**/build/**": true,
    "**/node_modules/**": true,
    "**/.next/**": true
  },
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": "always"
  },
  "editor.formatOnSave": true,
  "editor.formatOnSaveMode": "file",
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.maxTokenizationLineLength": 20000000,
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true
  },
  "[javascriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true
  },
  "eslint.enable": true,
  "eslint.useFlatConfig": true,
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact"
  ],
  "eslint.workingDirectories": ["./"],
  "debug.javascript.unmapMissingSources": true,
  "javascript.preferences.importModuleSpecifier": "relative",
  "typescript.preferences.importModuleSpecifier": "relative",
  "typescript.tsdk": "node_modules/typescript/lib",
  "typescript.validate.enable": true,
  "cSpell.ignorePaths": [
    "**/package-lock.json",
    "**/node_modules/**",
    "**/build/**",
    "**/vscode-extension/**",
    "**/.git/objects/**",
    ".vscode"
  ],
  "cSpell.words": ["arkit", "autogenerated", "scrollable", "serializable"]
}
`

    protected constructor(options: AutopackageOptions) {
        const {
            installDir,
            name,
            description,
            gitNamespace,
            npmNamespace,
            license,
            author,
            keywords,
        } = options

        this.installDir = installDir
        this.packageName = name
        this.description = description ?? ''
        this.gitNamespace = gitNamespace ?? ''
        this.npmNamespace = npmNamespace
        this.keywords = keywords
        this.license = license
        this.author = author

        this.packageDir = path.join(this.installDir, this.packageName)
        this.packageJsonPath = path.join(this.packageDir, 'package.json')
        this.gitignorePath = path.join(this.packageDir, '.gitignore')
        this.tsconfigPath = path.join(this.packageDir, 'tsconfig.json')
        this.tasksJsonPath = path.join(this.packageDir, '.vscode/tasks.json')
        this.testsDir = path.join(this.packageDir, 'src', '__tests__')

        this.abstractTestPath = path.join(
            this.testsDir,
            'AbstractPackageTest.ts'
        )

        this.eslintConfigPath = path.join(this.packageDir, 'eslint.config.js')

        this.prettierConfigPath = path.join(
            this.packageDir,
            'prettier.config.js'
        )

        this.settingsJsonPath = path.join(
            this.packageDir,
            '.vscode',
            'settings.json'
        )
    }

    public static Create(options: AutopackageOptions) {
        return new (this.Class ?? this)(options)
    }

    public async run() {
        console.info('Starting autopackage process...\n')
        this.throwIfGithubTokenNotInEnv()

        await this.createRepoInGithubOrg()
        await this.cloneGitRepo()
        await this.resetMainToOrigin()
        await this.setCurrentMetaNodeVersion()
        await this.updatePackageJson()
        await this.updateGitignore()
        await this.updateTsconfig()
        await this.updateVscodeTasks()
        await this.installDefaultDevDependencies()
        await this.installAbstractPackageTest()
        await this.installEslintConfigFile()
        await this.installPrettierConfigFile()
        await this.installSettingsJsonFile()
        await this.fixEslintAndPrettier()
        await this.commitChangesIfPresent()
        await this.openVscode()

        console.info('\nAutopackage process completed!\n')
    }

    private throwIfGithubTokenNotInEnv() {
        if (!this.githubToken) {
            throw new Error('\n\nPlease set process.env.GITHUB_TOKEN!\n')
        }
    }

    private get githubToken() {
        return process.env.GITHUB_TOKEN
    }

    private async createRepoInGithubOrg() {
        const repoExists = await this.checkIfRepoExists()

        if (!repoExists) {
            console.info('Creating repository in GitHub organization...')
            await this.submitCreateRepoRequest()
        }
    }

    private async checkIfRepoExists() {
        const response = await this.fetch(
            `https://api.github.com/repos/${this.gitNamespace}/${this.packageName}`,
            {
                method: 'GET',
                headers: {
                    Authorization: `token ${this.githubToken}`,
                    Accept: 'application/vnd.github+json',
                },
            }
        )
        return response.status === 200
    }

    private async submitCreateRepoRequest() {
        await this.fetch(
            `https://api.github.com/orgs/${this.gitNamespace}/repos`,
            {
                method: 'POST',
                headers: {
                    Authorization: `token ${this.githubToken}`,
                    Accept: 'application/vnd.github+json',
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    name: this.packageName,
                    private: false,
                    description: this.description,
                    auto_init: true,
                    gitignore_template: 'Node',
                    license_template: 'mit',
                }),
            }
        )
    }

    private async cloneGitRepo() {
        const packageDirExists = await this.checkIfPackageDirExists()

        if (!packageDirExists) {
            console.info('Cloning git repository...')

            await this.exec(`git clone ${this.gitUrl}`, {
                cwd: this.installDir,
            })
            this.shouldOpenVscode = true
        }
    }

    private async checkIfPackageDirExists() {
        return this.pathExists(this.packageDir)
    }

    private get gitUrl() {
        return `https://github.com/${this.gitNamespace}/${this.packageName}.git`
    }

    private async resetMainToOrigin() {
        await this.exec('git fetch origin', { cwd: this.packageDir })

        await this.exec('git reset --hard origin/main', {
            cwd: this.packageDir,
        })
    }

    private async setCurrentMetaNodeVersion() {
        const globalRoot = await this.exec('yarn global dir')

        const pkgPath = path.join(
            globalRoot.stdout.trim(),
            'node_modules',
            '@neurodevs',
            'meta-node',
            'package.json'
        )

        const raw = await this.readFile(pkgPath, { encoding: 'utf-8' })
        const pkg = JSON.parse(raw)

        this.metaNodeVersion = pkg.version
    }

    private async updatePackageJson() {
        this.originalPackageJson = await this.readJson(this.packageJsonPath)

        if (!this.isPackageUpToDate) {
            console.info('Updating package.json...')
            await this.updatePackageJsonFile()
        }
    }

    private async readJson(path: string) {
        return await this.readUtf8(path).then((raw) =>
            raw ? JSON.parse(raw) : undefined
        )
    }

    private async readUtf8(path: string) {
        return await this.readFile(path, { encoding: 'utf-8' }).catch(
            () => undefined
        )
    }

    private get isPackageUpToDate() {
        return (
            JSON.stringify(this.originalPackageJson) ===
            JSON.stringify(this.updatedPackageJson)
        )
    }

    private async updatePackageJsonFile() {
        this.removeOldKeysFromPackageJson()

        await this.writeFile(
            this.packageJsonPath,
            JSON.stringify(this.updatedPackageJson, null, 2) + '\n',
            { encoding: 'utf-8' }
        )
    }

    private removeOldKeysFromPackageJson() {
        const keysToRemove = [
            'jest.testPathIgnorePatterns',
            'scripts.build.resolve-paths',
            'scripts.lint.tsc',
            'scripts.post.watch.build',
            'scripts.resolve-paths.lint',
            'scripts.watch.rebuild',
            'scripts.watch.tsc',
        ]

        for (const key of keysToRemove) {
            this.deleteByPath(this.originalPackageJson ?? {}, key)
        }
    }

    private deleteByPath(obj: Record<string, unknown>, path: string): void {
        const dot = path.indexOf('.')

        if (dot === -1) {
            delete obj[path]
            return
        }

        const parentKey = path.slice(0, dot)
        const childKey = path.slice(dot + 1)

        const parent = obj[parentKey] as Record<string, unknown> | undefined

        if (parent) {
            delete parent[childKey]
        }
    }

    private get updatedPackageJson() {
        return this.orderJsonKeys(
            {
                ...this.packageJsonTemplate,
                ...this.originalPackageJson,
                scripts: {
                    ...this.packageJsonTemplate.scripts,
                    ...(this.originalPackageJson?.scripts || {}),
                },
                dependencies: {
                    ...this.packageJsonTemplate.dependencies,
                    ...(this.originalPackageJson?.dependencies || {}),
                },
                jest: {
                    ...this.packageJsonTemplate.jest,
                    ...(this.originalPackageJson?.jest || {}),
                },
            },
            [
                'name',
                'version',
                'description',
                'type',
                'keywords',
                'license',
                'author',
                'homepage',
                'repository',
                'bugs',
                'main',
                'bin',
                'files',
                'scripts',
                'dependencies',
                'devDependencies',
                'peerDependencies',
                'resolutions',
                'jest',
            ]
        )
    }

    private get packageJsonTemplate() {
        return {
            name: this.npmNamespace
                ? `@${this.npmNamespace}/${this.packageName}`
                : this.packageName,
            description: this.description,
            type: 'module',
            keywords: this.keywords,
            license: this.license,
            author: this.author,
            main: 'build/index.js',
            homepage: `https://github.com/${this.gitNamespace}/${this.packageName}`,
            repository: {
                type: 'git',
                url: `git+https://github.com/${this.gitNamespace}/${this.packageName}.git`,
            },
            bugs: {
                url: `https://github.com/${this.gitNamespace}/${this.packageName}/issues`,
            },
            scripts: {
                'build.ci': `yarn run build.tsc && yarn run lint`,
                'build.dev': `yarn run build.tsc --sourceMap ; yarn run fix.lint ; prettier --write . --log-level warn`,
                'build.copy-files': `mkdir -p build && rsync -avzq --exclude='*.ts' ./src/ ./build/`,
                'build.tsc': `yarn run build.copy-files && tsc`,
                clean: `yarn run clean.build`,
                'clean.all': `yarn run clean.dependencies && yarn run clean.build`,
                'clean.build': `rm -rf build/`,
                'clean.dependencies': `rm -rf node_modules/ package-lock.json yarn.lock`,
                'fix.lint': `eslint --fix --cache '**/*.ts'`,
                lint: `eslint --cache '**/*.ts'`,
                rebuild: `yarn run clean.all && yarn install && yarn run build.dev`,
                'update.dependencies': `yarn run clean.dependencies && yarn`,
                test: 'NODE_OPTIONS=--experimental-vm-modules jest',
                'watch.build.dev': `tsc-watch --sourceMap --onCompilationComplete 'yarn run build.copy-files'`,
            },
            dependencies: {},
            devDependencies: {},
            jest: {
                testEnvironment: 'node',
                testRunner: 'jest-circus/runner',
                testMatch: ['<rootDir>/build/__tests__/**/*.test.js?(x)'],
                testTimeout: 5000,
                maxWorkers: 4,
            },
        }
    }

    private orderJsonKeys(json: Record<string, unknown>, keyOrder: string[]) {
        const ordered: Record<string, any> = {}

        for (const key of keyOrder) {
            if (key in json) {
                ordered[key] = json[key]
            }
        }

        const remainingKeys = Object.keys(json)
            .filter((k) => !keyOrder.includes(k))
            .sort()

        for (const key of remainingKeys) {
            ordered[key] = json[key]
        }

        return ordered
    }

    private async updateGitignore() {
        this.originalGitignore = await this.readUtf8(this.gitignorePath)

        if (!this.isGitignoreUpdated) {
            console.info('Updating .gitignore...')

            await this.updateGitignoreFile()
        }
    }

    private get isGitignoreUpdated() {
        const lines = (this.originalGitignore ?? '')
            .split(/\r?\n/)
            .map((line) => line.trim())

        return lines.includes('build/')
    }

    private async updateGitignoreFile() {
        await this.writeFile(this.gitignorePath, '\nbuild/\n', {
            encoding: 'utf-8',
            flag: 'a',
        })
    }

    private async updateTsconfig() {
        this.originalTsconfig = await this.readJson(this.tsconfigPath)

        if (this.shouldUpdateTsconfig) {
            console.info('Updating tsconfig...')
            await this.updateTsconfigFile()
            await this.executeYarnBuildDev()
        }
    }

    private get shouldUpdateTsconfig() {
        return (
            JSON.stringify(this.originalTsconfig) !==
            JSON.stringify(this.updatedTsconfig)
        )
    }

    private async updateTsconfigFile() {
        await this.writeFile(
            this.tsconfigPath,
            JSON.stringify(this.updatedTsconfig, null, 2) + '\n',
            {
                encoding: 'utf-8',
            }
        )
    }

    private get updatedTsconfig(): TsConfig {
        return {
            ...this.tsconfigTemplate,
            ...this.originalTsconfig,
            compilerOptions: {
                ...this.tsconfigTemplate.compilerOptions,
                ...this.originalTsconfig?.compilerOptions,
                lib: [
                    ...(this.tsconfigTemplate.compilerOptions?.lib ?? []),
                    ...(
                        this.originalTsconfig?.compilerOptions?.lib ?? []
                    ).filter((v) => !v.toLowerCase().startsWith('es')),
                ],
                types: Array.from(
                    new Set([
                        'node',
                        ...(this.originalTsconfig?.compilerOptions?.types ??
                            []),
                    ])
                ),
            },
            include: Array.from(
                new Set([
                    './src/*.ts',
                    './src/**/*.ts',
                    ...(this.originalTsconfig?.include ?? []),
                ])
            ),
        }
    }

    private get tsconfigTemplate() {
        return {
            compilerOptions: {
                module: 'nodenext',
                target: 'esnext',
                lib: ['esnext'],
                types: ['node'],
                rootDir: 'src',
                outDir: 'build',
                sourceMap: false,
                strict: true,
                noImplicitAny: true,
                noImplicitReturns: true,
                noUnusedLocals: true,
                forceConsistentCasingInFileNames: true,
                declaration: true,
                skipLibCheck: true,
                esModuleInterop: true,
                moduleDetection: 'force',
                allowJs: true,
                resolveJsonModule: true,
                experimentalDecorators: true,
            },
            include: ['./src/*.ts', './src/**/*.ts'],
        }
    }

    private async updateVscodeTasks() {
        this.originalTasksJson = await this.readJson(this.tasksJsonPath)

        if (!this.isTasksJsonUpdated) {
            console.info('Updating vscode tasks...')
            await this.updateTasksJsonFile()
        }
    }

    private get isTasksJsonUpdated() {
        return (
            JSON.stringify(this.originalTasksJson, null, 2) ===
            this.updatedTasksJsonFile
        )
    }

    private async updateTasksJsonFile() {
        await this.writeFile(this.tasksJsonPath, this.updatedTasksJsonFile, {
            encoding: 'utf-8',
        })
    }

    private get updatedTasksJsonFile() {
        const mergedTasks = [
            ...this.tasksJsonTemplate.tasks,
            ...(this.originalTasksJson?.tasks ?? []),
        ].filter(
            (task: any, index, all: any[]) =>
                all.findIndex((t) => t.label === task.label) === index
        )

        const mergedInputs = [
            ...this.tasksJsonTemplate.inputs,
            ...(this.originalTasksJson?.inputs ?? []),
        ].filter(
            (input: any, index, all: any[]) =>
                all.findIndex((i) => i.id === input.id) === index
        )

        return JSON.stringify(
            {
                ...this.tasksJsonTemplate,
                ...this.originalTasksJson,
                tasks: mergedTasks,
                inputs: mergedInputs,
            },
            null,
            2
        )
    }

    private get tasksJsonTemplate() {
        return {
            version: '1.0.0',
            tasks: [
                {
                    type: 'npm',
                    script: 'watch.build.dev',
                    group: 'build',
                    label: 'watch.build.dev & problem.watcher',
                    isBackground: true,
                    runOptions: {
                        runOn: 'folderOpen',
                    },
                    promptOnClose: false,
                    presentation: {
                        focus: false,
                        reveal: 'never',
                    },
                    problemMatcher: {
                        base: '$tsc-watch',
                        applyTo: 'allDocuments',
                    },
                },
                {
                    label: 'test.file',
                    type: 'shell',
                    command:
                        'node node_modules/@neurodevs/node-tdd/build/workspace/testRunner.cli.js --pattern "${fileBasenameNoExtension}" --watchMode standard --inspect 5200',
                    promptOnClose: false,
                    group: {
                        kind: 'test',
                        isDefault: true,
                    },
                    presentation: {
                        reveal: 'always',
                        panel: 'dedicated',
                    },
                    problemMatcher: [],
                },
                {
                    label: 'test.reporter',
                    type: 'shell',
                    command:
                        'node node_modules/@neurodevs/node-tdd/build/workspace/testRunner.cli.js --watchMode standard',
                    promptOnClose: false,
                    group: 'test',
                    runOptions: {
                        runOn: 'folderOpen',
                    },
                    presentation: {
                        panel: 'shared',
                        focus: true,
                        reveal: 'always',
                    },
                    problemMatcher: [],
                },
                {
                    label: 'shell',
                    type: 'shell',
                    command: '${input:command} ${input:optionsCommand}',
                    problemMatcher: [],
                    presentation: {
                        reveal: 'always',
                        focus: true,
                        panel: 'new',
                        clear: false,
                    },
                },
                {
                    label: 'ndx',
                    type: 'shell',
                    command: 'ndx ${input:ndxCommand}',
                    problemMatcher: [],
                    presentation: {
                        reveal: 'always',
                        focus: true,
                        panel: 'new',
                        clear: false,
                    },
                },
            ],
            inputs: [
                {
                    id: 'command',
                    description: 'command',
                    default: 'yarn',
                    type: 'promptString',
                },
                {
                    id: 'optionsCommand',
                    description: 'optionsCommand',
                    default: 'add',
                    type: 'promptString',
                },
                {
                    id: 'ndxCommand',
                    description: 'ndx command',
                    default: 'create.module',
                    type: 'promptString',
                },
            ],
        }
    }

    private async installDefaultDevDependencies() {
        const testsDirExists = await this.pathExists(this.testsDir)

        if (!testsDirExists) {
            return
        }

        const generateIdVersion = await this.getLatestVersion(
            '@neurodevs/generate-id'
        )

        const nodeTddVersion = await this.getLatestVersion(
            '@neurodevs/node-tdd'
        )

        const eslintConfigNdxVersion = await this.getLatestVersion(
            '@neurodevs/eslint-config-ndx'
        )

        const prettierConfigNdxVersion = await this.getLatestVersion(
            '@neurodevs/prettier-config-ndx'
        )

        if (
            this.currentGenerateIdVersion != generateIdVersion ||
            this.currentNodeTddVersion != nodeTddVersion ||
            this.currentEslintConfigNdxVersion != eslintConfigNdxVersion ||
            this.currentPrettierConfigNdxVersion != prettierConfigNdxVersion
        ) {
            console.info('Installing default devDependencies...')

            await this.exec(
                'yarn add -D @neurodevs/generate-id @neurodevs/node-tdd @neurodevs/eslint-config-ndx @neurodevs/prettier-config-ndx prettier',
                { cwd: this.packageDir }
            )
        }
    }

    private async getLatestVersion(scopedPackageName: string) {
        const { stdout } = await this.exec(
            `yarn info ${scopedPackageName} version --silent`,
            { cwd: this.packageDir }
        )
        return stdout.trim()
    }

    private get currentGenerateIdVersion() {
        return (
            (this.originalPackageJson?.devDependencies || ({} as any))[
                '@neurodevs/generate-id'
            ] ||
            (this.originalPackageJson?.dependencies || ({} as any))[
                '@neurodevs/generate-id'
            ] ||
            ''
        ).replace('^', '')
    }

    private get currentNodeTddVersion() {
        return (
            (this.originalPackageJson?.devDependencies || ({} as any))[
                '@neurodevs/node-tdd'
            ] ||
            (this.originalPackageJson?.dependencies || ({} as any))[
                '@neurodevs/node-tdd'
            ] ||
            ''
        ).replace('^', '')
    }

    private get currentEslintConfigNdxVersion() {
        return (
            (this.originalPackageJson?.devDependencies || ({} as any))[
                '@neurodevs/eslint-config-ndx'
            ] ||
            (this.originalPackageJson?.dependencies || ({} as any))[
                '@neurodevs/eslint-config-ndx'
            ] ||
            ''
        ).replace('^', '')
    }

    private get currentPrettierConfigNdxVersion() {
        return (
            (this.originalPackageJson?.devDependencies || ({} as any))[
                '@neurodevs/prettier-config-ndx'
            ] ||
            (this.originalPackageJson?.dependencies || ({} as any))[
                '@neurodevs/prettier-config-ndx'
            ] ||
            ''
        ).replace('^', '')
    }

    private async installAbstractPackageTest() {
        const shouldInstall = await this.checkShouldInstallAbstractTest()

        if (shouldInstall) {
            console.info(`Installing ${this.abstractTestPath}...`)

            await this.mkdir(this.testsDir, { recursive: true })

            await this.writeFile(
                this.abstractTestPath,
                this.abstractPackageTestFile,
                {
                    encoding: 'utf-8',
                }
            )
        }
    }

    private async checkShouldInstallAbstractTest() {
        const doesTestsDirExist = await this.pathExists(this.testsDir)
        const doesTsExist = await this.pathExists(this.abstractTestPath)
        const doesTsxExist = await this.pathExists(`${this.abstractTestPath}x`)

        return !(doesTsExist || doesTsxExist) && doesTestsDirExist
    }

    private async installEslintConfigFile() {
        this.originalEslintConfig = await this.loadEslintConfigFile()

        if (this.shouldUpdateEslintConfig) {
            console.info('Installing eslint.config.js...')

            await this.writeFile(this.eslintConfigPath, this.eslintConfigFile, {
                encoding: 'utf-8',
            })
        }
    }

    private async loadEslintConfigFile() {
        try {
            return await this.readFile(this.eslintConfigPath, {
                encoding: 'utf-8',
            })
        } catch {
            return ''
        }
    }

    private get shouldUpdateEslintConfig() {
        return (
            this.originalEslintConfig?.trim() !==
                this.eslintConfigFile.trim() &&
            this.packageName !== 'eslint-config-ndx'
        )
    }

    private async installPrettierConfigFile() {
        this.originalPrettierConfig = await this.loadPrettierConfigFile()

        if (this.shouldUpdatePrettierConfig) {
            console.info('Installing prettier.config.js...')

            await this.writeFile(
                this.prettierConfigPath,
                this.prettierConfigFile,
                {
                    encoding: 'utf-8',
                }
            )
        }
    }

    private async loadPrettierConfigFile() {
        try {
            return await this.readFile(this.prettierConfigPath, {
                encoding: 'utf-8',
            })
        } catch {
            return ''
        }
    }

    private get shouldUpdatePrettierConfig() {
        return (
            this.originalPrettierConfig?.trim() !==
                this.prettierConfigFile.trim() &&
            this.packageName !== 'prettier-config-ndx'
        )
    }

    private async installSettingsJsonFile() {
        this.originalSettingsJson = await this.loadSettingsJsonFile()

        if (!this.settingsJsonIsUpToDate) {
            console.info('Installing .vscode/settings.json...')

            await this.writeFile(this.settingsJsonPath, this.settingsJsonFile, {
                encoding: 'utf-8',
            })
        }
    }

    private async loadSettingsJsonFile() {
        return await this.readFile(this.settingsJsonPath, {
            encoding: 'utf-8',
        }).catch(() => undefined)
    }

    private get settingsJsonIsUpToDate() {
        return (
            this.originalSettingsJson?.trim() === this.settingsJsonFile.trim()
        )
    }

    private async fixEslintAndPrettier() {
        console.info('Fixing eslint and prettier...')
        await this.executeYarnBuildDev()
    }

    private async executeYarnBuildDev() {
        await this.exec('yarn build.dev', {
            cwd: this.packageDir,
        })
    }

    private async commitChangesIfPresent() {
        const hasChanges = await this.hasGitChanges()

        if (hasChanges) {
            await this.GitAutocommit(
                `patch: autopackage changes (@neurodevs/meta-node: ${this.metaNodeVersion})`
            )
        }
    }

    private async hasGitChanges() {
        const { stdout } = await this.exec('git status --porcelain', {
            cwd: this.packageDir,
        })
        return stdout.trim() !== ''
    }

    private async openVscode() {
        if (this.shouldOpenVscode) {
            console.info('Opening VSCode...')

            await this.exec('code . --reuse-window --reload-window', {
                cwd: this.packageDir,
            })
        }
    }

    private get exec() {
        return NpmAutopackage.exec
    }

    private get fetch() {
        return NpmAutopackage.fetch
    }

    private get mkdir() {
        return NpmAutopackage.mkdir
    }

    private get pathExists() {
        return NpmAutopackage.pathExists
    }

    private get readFile() {
        return NpmAutopackage.readFile
    }

    private get writeFile() {
        return NpmAutopackage.writeFile
    }

    private async GitAutocommit(commitMessage: string) {
        return GitAutocommit.Create(commitMessage, this.packageDir)
    }
}

export interface Autopackage {
    run(): Promise<void>
}

export interface AutopackageOptions {
    installDir: string
    name: string
    description?: string
    gitNamespace?: string
    npmNamespace?: string
    keywords?: string[]
    license?: string
    author?: string
}

export type AutopackageConstructor = new (
    options: AutopackageOptions
) => Autopackage

export interface TsConfig {
    compilerOptions?: {
        lib?: string[]
        types?: string[]
        [key: string]: unknown
    }
    include?: string[]
    [key: string]: unknown
}
