import { exec as execSync } from 'child_process'
import { mkdir, readFile, writeFile } from 'fs/promises'
import path from 'path'
import { promisify } from 'util'
import { pathExists } from 'fs-extra'
import { parse } from 'jsonc-parser'

import GitAutocommit from './GitAutocommit.js'

export default class NpmAutopackage implements Autopackage {
    public static Class?: AutopackageConstructor
    public static exec = promisify(execSync)
    public static fetch = fetch
    public static mkdir = mkdir
    public static pathExists = pathExists
    public static readFile = readFile
    public static writeFile = writeFile

    private description: string
    private gitNamespace: string
    private npmNamespace?: string
    private keywords?: string[]
    private license?: string
    private author?: string

    private originalPackageJson!: Record<string, unknown>
    private originalGitignore!: string

    private originalTsconfig!: TsConfig
    private metaNodeVersion!: string

    private originalEslintConfig!: string
    private originalPrettierConfig!: string
    private originalSettingsJson!: string

    private originalTasksJson!: {
        tasks: unknown[]
        inputs: unknown[]
        [key: string]: unknown
    }

    private shouldOpenVscode = false

    private readonly installDir: string
    private readonly packageName: string
    private readonly packageDir: string
    private readonly packageJsonPath: string
    private readonly gitignorePath: string
    private readonly tsconfigPath: string
    private readonly tasksJsonPath: string
    private readonly testsDir: string
    private readonly abstractTestPath: string
    private readonly eslintConfigPath: string
    private readonly prettierConfigPath: string
    private readonly settingsJsonPath: string

    private readonly abstractPackageTestFile = `import AbstractModuleTest from '@neurodevs/node-tdd'

export default abstract class AbstractPackageTest extends AbstractModuleTest {
    protected static async beforeEach() {
        await super.beforeEach()
    }
}
`

    private readonly eslintConfigFile = `import eslintConfigNdx from '@neurodevs/eslint-config-ndx'

export default eslintConfigNdx
`

    private readonly prettierConfigFile = `import prettierConfigNdx from '@neurodevs/prettier-config-ndx'

export default prettierConfigNdx
`

    private readonly settingsJsonFile = `{
  "debug.node.autoAttach": "on",
  "git.ignoreLimitWarning": true,
  "javascript.validate.enable": false,
  "files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/.git/subtree-cache/**": true,
    "**/build/**": true,
    "**/node_modules/**": true
  },
  "search.exclude": {
    "**/build/**": true,
    "**/node_modules/**": true,
    "**/.next/**": true
  },
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": "always"
  },
  "editor.formatOnSave": true,
  "editor.formatOnSaveMode": "file",
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.maxTokenizationLineLength": 20000000,
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true
  },
  "[javascriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true
  },
  "eslint.enable": true,
  "eslint.useFlatConfig": true,
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact"
  ],
  "eslint.workingDirectories": ["./"],
  "debug.javascript.unmapMissingSources": true,
  "javascript.preferences.importModuleSpecifier": "relative",
  "typescript.preferences.importModuleSpecifier": "relative",
  "typescript.tsdk": "node_modules/typescript/lib",
  "typescript.validate.enable": true,
  "cSpell.ignorePaths": [
    "**/package-lock.json",
    "**/node_modules/**",
    "**/build/**",
    "**/vscode-extension/**",
    "**/.git/objects/**",
    ".vscode",
    ".spruce"
  ],
  "cSpell.words": ["arkit", "autogenerated", "scrollable", "serializable"]
}
`

    protected constructor(options: AutopackageOptions) {
        const {
            installDir,
            name,
            description,
            gitNamespace,
            npmNamespace,
            license,
            author,
            keywords,
        } = options

        this.installDir = installDir
        this.packageName = name
        this.description = description
        this.gitNamespace = gitNamespace
        this.npmNamespace = npmNamespace
        this.keywords = keywords
        this.license = license
        this.author = author

        this.packageDir = path.join(this.installDir, this.packageName)
        this.packageJsonPath = path.join(this.packageDir, 'package.json')
        this.gitignorePath = path.join(this.packageDir, '.gitignore')
        this.tsconfigPath = path.join(this.packageDir, 'tsconfig.json')
        this.tasksJsonPath = path.join(this.packageDir, '.vscode/tasks.json')
        this.testsDir = path.join(this.packageDir, 'src', '__tests__')

        this.abstractTestPath = path.join(
            this.testsDir,
            'AbstractPackageTest.ts'
        )

        this.eslintConfigPath = path.join(this.packageDir, 'eslint.config.js')

        this.prettierConfigPath = path.join(
            this.packageDir,
            'prettier.config.js'
        )

        this.settingsJsonPath = path.join(
            this.packageDir,
            '.vscode',
            'settings.json'
        )
    }

    public static Create(options: AutopackageOptions) {
        return new (this.Class ?? this)(options)
    }

    public async run() {
        this.throwIfGithubTokenNotInEnv()

        await this.createRepoInGithubOrg()
        await this.cloneGitRepo()
        await this.resetMainToOrigin()
        await this.setCurrentMetaNodeVersion()
        await this.spruceCreateModule()
        await this.updatePackageJson()
        await this.updateGitignore()
        await this.updateTsconfig()
        await this.setupVscode()
        await this.updateVscodeTasks()
        await this.installDefaultDevDependencies()
        await this.installAbstractPackageTest()
        await this.installEslintConfigFile()
        await this.installPrettierConfigFile()
        await this.installSettingsJsonFile()
        await this.openVscode()
    }

    private throwIfGithubTokenNotInEnv() {
        if (!this.githubToken) {
            throw new Error('\n\nPlease set process.env.GITHUB_TOKEN!\n')
        }
    }

    private get githubToken() {
        return process.env.GITHUB_TOKEN
    }

    private async createRepoInGithubOrg() {
        const repoExists = await this.checkIfRepoExists()

        if (!repoExists) {
            console.log('Creating repository in GitHub organization...')
            await this.submitCreateRepoRequest()
        }
    }

    private async checkIfRepoExists() {
        const response = await this.fetch(
            `https://api.github.com/repos/${this.gitNamespace}/${this.packageName}`,
            {
                method: 'GET',
                headers: {
                    Authorization: `token ${this.githubToken}`,
                    Accept: 'application/vnd.github+json',
                },
            }
        )
        return response.status === 200
    }

    private async submitCreateRepoRequest() {
        await this.fetch(
            `https://api.github.com/orgs/${this.gitNamespace}/repos`,
            {
                method: 'POST',
                headers: {
                    Authorization: `token ${this.githubToken}`,
                    Accept: 'application/vnd.github+json',
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    name: this.packageName,
                    private: false,
                    description: this.description,
                    auto_init: true,
                    gitignore_template: 'Node',
                    license_template: 'mit',
                }),
            }
        )
    }

    private async cloneGitRepo() {
        const packageDirExists = await this.checkIfPackageDirExists()

        if (!packageDirExists) {
            console.log('Cloning git repository...')

            await this.exec(`git clone ${this.gitUrl}`, {
                cwd: this.installDir,
            })
            this.shouldOpenVscode = true
        }
    }

    private async checkIfPackageDirExists() {
        return this.pathExists(this.packageDir)
    }

    private get gitUrl() {
        return `https://github.com/${this.gitNamespace}/${this.packageName}.git`
    }

    private async resetMainToOrigin() {
        await this.exec('git fetch origin', { cwd: this.packageDir })

        await this.exec('git reset --hard origin/main', {
            cwd: this.packageDir,
        })
    }

    private async setCurrentMetaNodeVersion() {
        const globalRoot = await this.exec('yarn global dir')

        const pkgPath = path.join(
            globalRoot.stdout.trim(),
            'node_modules',
            '@neurodevs',
            'meta-node',
            'package.json'
        )

        const raw = await this.readFile(pkgPath, { encoding: 'utf-8' })
        const pkg = JSON.parse(raw)

        this.metaNodeVersion = pkg.version
    }

    private async spruceCreateModule() {
        const packageJsonExists = await this.checkIfPackageJsonExists()

        if (!packageJsonExists) {
            console.log('Running spruce create.module...')

            await this.execSpruceCreateModule()
            await this.commitCreatePackage()
        }
    }

    private async checkIfPackageJsonExists() {
        return this.pathExists(this.packageJsonPath)
    }

    private async execSpruceCreateModule() {
        await this.exec(
            `spruce create.module --name "${this.packageName}" --destination "." --description "${this.description}"`,
            { cwd: this.packageDir }
        )
    }

    private async commitCreatePackage() {
        await this.GitAutocommit(
            `patch: create package (@neurodevs/meta-node: ${this.metaNodeVersion})`
        )
    }

    private async updatePackageJson() {
        this.originalPackageJson = await this.loadPackageJson()

        if (!this.isPackageUpToDate) {
            console.log('Updating package.json...')

            await this.updatePackageJsonFile()
            await this.commitUpdatePackageJson()
        }
    }

    private async loadPackageJson() {
        const raw = await this.readFile(this.packageJsonPath, {
            encoding: 'utf-8',
        })
        return JSON.parse(raw)
    }

    private get isPackageUpToDate() {
        return (
            JSON.stringify(this.originalPackageJson) ==
            JSON.stringify(this.updatedPackageJson)
        )
    }

    private async updatePackageJsonFile() {
        this.removeOldKeysFromPackageJson()

        const ordered = this.orderJsonKeys(this.updatedPackageJson, [
            'name',
            'version',
            'description',
            'type',
            'keywords',
            'license',
            'author',
            'homepage',
            'repository',
            'bugs',
            'main',
            'bin',
            'files',
            'scripts',
            'dependencies',
            'devDependencies',
            'jest',
        ])

        await this.writeFile(
            this.packageJsonPath,
            JSON.stringify(ordered, null, 2) + '\n',
            { encoding: 'utf-8' }
        )
    }

    private removeOldKeysFromPackageJson() {
        const keysToRemove = [
            'skill',
            'jest.testPathIgnorePatterns',
            'jest.moduleNameMapper',
            'scripts.build.resolve-paths',
            'scripts.lint.tsc',
            'scripts.post.watch.build',
            'scripts.resolve-paths.lint',
            'scripts.watch.rebuild',
            'scripts.watch.tsc',
        ]

        for (const key of keysToRemove) {
            this.deleteByPath(this.originalPackageJson, key)
        }
    }

    private deleteByPath(obj: any, path: string): void {
        const dot = path.indexOf('.')

        if (dot === -1) {
            delete obj[path]
            return
        }

        const parentKey = path.slice(0, dot)
        const childKey = path.slice(dot + 1)

        const parent = obj[parentKey]

        if (parent) {
            delete parent[childKey]
        }
    }

    private get updatedPackageJson() {
        return {
            ...this.originalPackageJson,
            name: this.scopedPackageName,
            description: this.description,
            type: 'module',
            keywords: this.keywords ?? [],
            license: this.license,
            author: this.author,
            main: 'build/index.js',
            homepage: `https://github.com/${this.gitNamespace}/${this.packageName}`,
            repository: {
                type: 'git',
                url: `git+https://github.com/${this.gitNamespace}/${this.packageName}.git`,
            },
            bugs: {
                url: `https://github.com/${this.gitNamespace}/${this.packageName}/issues`,
            },
            scripts: {
                ...(this.originalPackageJson.scripts ?? {}),
                'build.ci': 'yarn run build.tsc && yarn run lint',
                'build.dev':
                    'yarn run build.tsc --sourceMap ; yarn run lint ; prettier --write .',
                'build.copy-files':
                    "mkdir -p build && rsync -avzq --exclude='*.ts' ./src/ ./build/",
                'build.tsc': 'yarn run build.copy-files && tsc',
                clean: 'yarn run clean.build',
                'clean.all':
                    'yarn run clean.dependencies && yarn run clean.build',
                'clean.build': 'rm -rf build/',
                'clean.dependencies':
                    'rm -rf node_modules/ package-lock.json yarn.lock',
                'fix.lint': "eslint --fix --cache '**/*.ts'",
                lint: "eslint --cache '**/*.ts'",
                rebuild:
                    'yarn run clean.all && yarn install && yarn run build.dev',
                'update.dependencies': 'yarn run clean.dependencies && yarn',
                test: 'NODE_OPTIONS=--experimental-vm-modules jest',
                'watch.build.dev':
                    "tsc-watch --sourceMap --onCompilationComplete 'yarn run build.copy-files'",
            },
            dependencies: this.originalPackageJson.dependencies ?? {},
            jest: {
                ...(this.originalPackageJson.jest ?? {}),
                testEnvironment: 'node',
                testRunner: 'jest-circus/runner',
                testMatch: ['<rootDir>/build/__tests__/**/*.test.js?(x)'],
                testTimeout: 5000,
                maxWorkers: 4,
            },
        }
    }

    private get scopedPackageName() {
        return this.npmNamespace
            ? `@${this.npmNamespace}/${this.packageName}`
            : this.packageName
    }

    private orderJsonKeys(json: Record<string, unknown>, keyOrder: string[]) {
        const ordered: Record<string, any> = {}

        for (const key of keyOrder) {
            if (key in json) {
                ordered[key] = json[key]
            }
        }

        const remainingKeys = Object.keys(json)
            .filter((k) => !keyOrder.includes(k))
            .sort()

        for (const key of remainingKeys) {
            ordered[key] = json[key]
        }

        return ordered
    }

    private async commitUpdatePackageJson() {
        await this.GitAutocommit(
            `patch: update package.json (@neurodevs/meta-node: ${this.metaNodeVersion})`
        )
    }

    private async updateGitignore() {
        this.originalGitignore = await this.loadGitignore()

        if (!this.isGitignoreUpdated) {
            console.log('Updating .gitignore...')

            await this.updateGitignoreFile()
            await this.commitUpdateGitignore()
        }
    }

    private async loadGitignore() {
        return await this.readFile(this.gitignorePath, {
            encoding: 'utf-8',
        })
    }

    private get isGitignoreUpdated() {
        const lines = this.originalGitignore
            .split(/\r?\n/)
            .map((line) => line.trim())

        return lines.includes('build/')
    }

    private async updateGitignoreFile() {
        await this.writeFile(this.gitignorePath, '\nbuild/\n', {
            encoding: 'utf-8',
            flag: 'a',
        })
    }

    private async commitUpdateGitignore() {
        await this.GitAutocommit(
            `patch: add build dir to gitignore (@neurodevs/meta-node: ${this.metaNodeVersion})`
        )
    }

    private async updateTsconfig() {
        this.originalTsconfig = await this.loadTsconfig()

        if (!this.isTsconfigUpdated) {
            console.log('Updating tsconfig...')
            await this.updateTsconfigFile()
            await this.commitUpdateTsconfig()
        }
    }

    private async loadTsconfig() {
        const raw = await this.readFile(this.tsconfigPath, {
            encoding: 'utf-8',
        })
        return JSON.parse(raw)
    }

    private get isTsconfigUpdated() {
        return (
            JSON.stringify(this.originalTsconfig) ==
            JSON.stringify(this.updatedTsconfig)
        )
    }

    private async updateTsconfigFile() {
        await this.writeFile(
            this.tsconfigPath,
            JSON.stringify(this.updatedTsconfig, null, 4) + '\n',
            {
                encoding: 'utf-8',
                flag: 'a',
            }
        )
    }

    private get updatedTsconfig() {
        return {
            ...this.originalTsconfig,
            compilerOptions: {
                module: 'nodenext',
                moduleResolution: 'nodenext',
                target: 'ES2022',
                lib: Array.from(
                    new Set([
                        ...(this.originalTsconfig?.compilerOptions?.lib ?? []),
                        'ES2022',
                    ])
                ),
                types: Array.from(
                    new Set([
                        ...(this.originalTsconfig?.compilerOptions?.types ??
                            []),
                        'node',
                    ])
                ),
                baseUrl: 'src',
                outDir: 'build',
                sourceMap: false,
                strict: true,
                noImplicitAny: true,
                noImplicitReturns: true,
                noUnusedLocals: true,
                forceConsistentCasingInFileNames: true,
                declaration: true,
                skipLibCheck: true,
                esModuleInterop: true,
                moduleDetection: 'force',
                allowJs: true,
                resolveJsonModule: true,
                experimentalDecorators: true,
            },
            include: Array.from(
                new Set([
                    ...(this.originalTsconfig?.include ?? []),
                    './src/*.ts',
                    './src/**/*.ts',
                ])
            ),
        }
    }

    private async commitUpdateTsconfig() {
        await this.GitAutocommit(
            `patch: update tsconfig (@neurodevs/meta-node: ${this.metaNodeVersion})`
        )
    }

    private async setupVscode() {
        const vscodeTasksExist = await this.checkIfVscodeTasksExist()

        if (!vscodeTasksExist) {
            console.log('Setting up VSCode...')

            await this.spruceSetupVscode()
            await this.commitSetupVscode()
        }
    }

    private async checkIfVscodeTasksExist() {
        return this.pathExists(this.tasksJsonPath)
    }

    private async spruceSetupVscode() {
        await this.exec('spruce setup.vscode --all true', {
            cwd: this.packageDir,
        })
    }

    private async commitSetupVscode() {
        await this.GitAutocommit(
            `patch: setup vscode (@neurodevs/meta-node: ${this.metaNodeVersion})`
        )
    }

    private async updateVscodeTasks() {
        this.originalTasksJson = await this.loadTasksJsonFile()

        if (!this.isTasksJsonUpdated) {
            console.log('Updating vscode tasks...')
            await this.updateTasksJsonFile()
            await this.commitUpdateVscodeTasks()
        }
    }

    private async updateTasksJsonFile() {
        await this.writeFile(this.tasksJsonPath, this.updatedTasksJsonFile, {
            encoding: 'utf-8',
        })
    }

    private get isTasksJsonUpdated() {
        return this.isTaskUpdated && this.isInputUpdated
    }

    private get isTaskUpdated() {
        return this.originalTasksJson.tasks.some(
            (task) => JSON.stringify(task) === JSON.stringify(this.requiredTask)
        )
    }

    private get isInputUpdated() {
        return this.originalTasksJson.inputs.some(
            (input) =>
                JSON.stringify(input) === JSON.stringify(this.requiredInput)
        )
    }

    private async loadTasksJsonFile() {
        const raw = await this.readFile(this.tasksJsonPath, {
            encoding: 'utf-8',
        })
        return parse(raw)
    }

    private get updatedTasksJsonFile() {
        return JSON.stringify(
            {
                ...this.originalTasksJson,
                tasks: [...this.originalTasksJson.tasks, this.requiredTask],
                inputs: [...this.originalTasksJson.inputs, this.requiredInput],
            },
            null,
            4
        )
    }

    private get requiredTask() {
        return {
            label: 'ndx',
            type: 'shell',
            command: 'ndx ${input:ndxCommand}',
            problemMatcher: [],
            presentation: {
                reveal: 'always',
                focus: true,
                panel: 'new',
                clear: false,
            },
        }
    }

    private get requiredInput() {
        return {
            id: 'ndxCommand',
            description: 'ndx command',
            default: 'create.module',
            type: 'promptString',
        }
    }

    private async commitUpdateVscodeTasks() {
        await this.GitAutocommit(
            `patch: update vscode tasks.json (@neurodevs/meta-node: ${this.metaNodeVersion})`
        )
    }

    private async installDefaultDevDependencies() {
        await this.removeOldDevDependencies()

        const testsDirExists = await this.pathExists(this.testsDir)

        if (!testsDirExists) {
            return
        }

        const generateIdVersion = await this.getLatestVersion(
            '@neurodevs/generate-id'
        )

        const nodeTddVersion = await this.getLatestVersion(
            '@neurodevs/node-tdd'
        )

        const eslintConfigNdxVersion = await this.getLatestVersion(
            '@neurodevs/eslint-config-ndx'
        )

        const prettierConfigNdxVersion = await this.getLatestVersion(
            '@neurodevs/prettier-config-ndx'
        )

        if (
            this.currentGenerateIdVersion != generateIdVersion ||
            this.currentNodeTddVersion != nodeTddVersion ||
            this.currentEslintConfigNdxVersion != eslintConfigNdxVersion ||
            this.currentPrettierConfigNdxVersion != prettierConfigNdxVersion
        ) {
            console.log('Installing default devDependencies...')

            await this.exec(
                'yarn add -D @neurodevs/generate-id @neurodevs/node-tdd @neurodevs/eslint-config-ndx @neurodevs/prettier-config-ndx prettier',
                { cwd: this.packageDir }
            )
            await this.commitInstallDevDependencies()
        }
    }

    private async removeOldDevDependencies() {
        if (this.oldDevDependencies.length > 0) {
            console.log('Removing old devDependencies...')

            await this.exec(
                `yarn remove ${this.oldDevDependencies.join(' ')}`,
                { cwd: this.packageDir }
            )
        }
    }

    private get oldDevDependencies() {
        return Object.keys(this.originalPackageJson.devDependencies!).filter(
            (dep) =>
                [
                    'eslint',
                    'eslint-config-spruce',
                    'chokidar-cli',
                    'ts-node',
                    '@types/node',
                ].includes(dep)
        )
    }

    private async getLatestVersion(scopedPackageName: string) {
        const { stdout } = await this.exec(
            `yarn info ${scopedPackageName} version --silent`,
            { cwd: this.packageDir }
        )
        return stdout.trim()
    }

    private get currentGenerateIdVersion() {
        return (
            (this.originalPackageJson.devDependencies as any)[
                '@neurodevs/generate-id'
            ] ||
            (this.originalPackageJson.dependencies as any)[
                '@neurodevs/generate-id'
            ] ||
            ''
        ).replace('^', '')
    }

    private get currentNodeTddVersion() {
        return (
            (this.originalPackageJson.devDependencies as any)[
                '@neurodevs/node-tdd'
            ] ||
            (this.originalPackageJson.dependencies as any)[
                '@neurodevs/node-tdd'
            ] ||
            ''
        ).replace('^', '')
    }

    private get currentEslintConfigNdxVersion() {
        return (
            (this.originalPackageJson.devDependencies as any)[
                '@neurodevs/eslint-config-ndx'
            ] ||
            (this.originalPackageJson.dependencies as any)[
                '@neurodevs/eslint-config-ndx'
            ] ||
            ''
        ).replace('^', '')
    }

    private get currentPrettierConfigNdxVersion() {
        return (
            (this.originalPackageJson.devDependencies as any)[
                '@neurodevs/prettier-config-ndx'
            ] ||
            (this.originalPackageJson.dependencies as any)[
                '@neurodevs/prettier-config-ndx'
            ] ||
            ''
        ).replace('^', '')
    }

    private async commitInstallDevDependencies() {
        await this.GitAutocommit(
            `patch: install default devDependencies (@neurodevs/meta-node: ${this.metaNodeVersion})`
        )
    }

    private async installAbstractPackageTest() {
        const shouldInstall = await this.checkShouldInstallAbstractTest()

        if (shouldInstall) {
            console.log(`Installing ${this.abstractTestPath}...`)

            await this.mkdir(this.testsDir, { recursive: true })

            await this.writeFile(
                this.abstractTestPath,
                this.abstractPackageTestFile,
                {
                    encoding: 'utf-8',
                }
            )

            await this.commitInstallAbstractPackageTest()
        }
    }

    private async checkShouldInstallAbstractTest() {
        const doesTestsDirExist = await this.pathExists(this.testsDir)
        const doesTsExist = await this.pathExists(this.abstractTestPath)
        const doesTsxExist = await this.pathExists(`${this.abstractTestPath}x`)

        return !(doesTsExist || doesTsxExist) && doesTestsDirExist
    }

    private async commitInstallAbstractPackageTest() {
        await this.GitAutocommit(
            `patch: install AbstractPackageTest (@neurodevs/meta-node: ${this.metaNodeVersion})`
        )
    }

    private async installEslintConfigFile() {
        await this.removeOldEslintConfigMjs()

        this.originalEslintConfig = await this.loadEslintConfigFile()

        if (this.shouldUpdateEslintConfig) {
            console.log('Installing eslint.config.js...')

            await this.writeFile(this.eslintConfigPath, this.eslintConfigFile, {
                encoding: 'utf-8',
            })

            await this.commitInstallEslintConfigFile()
        }
    }

    private async removeOldEslintConfigMjs() {
        const fileExists = await this.pathExists(
            path.join(this.packageDir, 'eslint.config.mjs')
        )

        if (fileExists) {
            console.log('Removing old eslint.config.mjs...')

            await this.exec(`git rm eslint.config.mjs`, {
                cwd: this.packageDir,
            })
        }
    }

    private async loadEslintConfigFile() {
        try {
            return await this.readFile(this.eslintConfigPath, {
                encoding: 'utf-8',
            })
        } catch {
            return ''
        }
    }

    private get shouldUpdateEslintConfig() {
        return (
            this.originalEslintConfig.trim() !== this.eslintConfigFile.trim() &&
            this.packageName !== 'eslint-config-ndx'
        )
    }

    private async commitInstallEslintConfigFile() {
        await this.GitAutocommit(
            `patch: install eslint.config.js (@neurodevs/meta-node: ${this.metaNodeVersion})`
        )
    }

    private async installPrettierConfigFile() {
        this.originalPrettierConfig = await this.loadPrettierConfigFile()

        if (this.shouldUpdatePrettierConfig) {
            console.log('Installing prettier.config.js...')

            await this.writeFile(
                this.prettierConfigPath,
                this.prettierConfigFile,
                {
                    encoding: 'utf-8',
                }
            )

            await this.commitInstallPrettierConfigFile()
        }
    }

    private async loadPrettierConfigFile() {
        try {
            return await this.readFile(this.prettierConfigPath, {
                encoding: 'utf-8',
            })
        } catch {
            return ''
        }
    }

    private get shouldUpdatePrettierConfig() {
        return (
            this.originalPrettierConfig.trim() !==
                this.prettierConfigFile.trim() &&
            this.packageName !== 'prettier-config-ndx'
        )
    }

    private async commitInstallPrettierConfigFile() {
        await this.GitAutocommit(
            `patch: install prettier.config.js (@neurodevs/meta-node: ${this.metaNodeVersion})`
        )
    }

    private async installSettingsJsonFile() {
        this.originalSettingsJson = await this.loadSettingsJsonFile()

        if (!this.settingsJsonIsUpToDate) {
            console.log('Installing .vscode/settings.json...')

            await this.writeFile(this.settingsJsonPath, this.settingsJsonFile, {
                encoding: 'utf-8',
            })

            await this.commitInstallSettingsJsonFile()
        }
    }

    private async loadSettingsJsonFile() {
        return await this.readFile(this.settingsJsonPath, {
            encoding: 'utf-8',
        })
    }

    private get settingsJsonIsUpToDate() {
        return this.originalSettingsJson.trim() === this.settingsJsonFile.trim()
    }

    private async commitInstallSettingsJsonFile() {
        await this.GitAutocommit(
            `patch: install settings.json (@neurodevs/meta-node: ${this.metaNodeVersion})`
        )
    }

    private async openVscode() {
        if (this.shouldOpenVscode) {
            await this.exec('code . --reuse-window --reload-window', {
                cwd: this.packageDir,
            })
        }
    }

    private get exec() {
        return NpmAutopackage.exec
    }

    private get fetch() {
        return NpmAutopackage.fetch
    }

    private get mkdir() {
        return NpmAutopackage.mkdir
    }

    private get pathExists() {
        return NpmAutopackage.pathExists
    }

    private get readFile() {
        return NpmAutopackage.readFile
    }

    private get writeFile() {
        return NpmAutopackage.writeFile
    }

    private GitAutocommit(commitMessage: string) {
        return GitAutocommit.Create(commitMessage, this.packageDir)
    }
}

export interface Autopackage {
    run(): Promise<void>
}

export interface AutopackageOptions {
    installDir: string
    name: string
    description: string
    gitNamespace: string
    npmNamespace?: string
    keywords?: string[]
    license?: string
    author?: string
}

export type AutopackageConstructor = new (
    options: AutopackageOptions
) => Autopackage

export interface TsConfig {
    compilerOptions?: {
        lib?: string[]
        types?: string[]
        [key: string]: unknown
    }
    include?: string[]
    [key: string]: unknown
}
